---
title: "Drug Use Exposed!"
description: "Unveiling the Factors of Influences for People with Drugs"
toc: true
draft: FALSE
---

## Debunking Myths: Race, Income, and Drug Use Dynamics

There are many stereotypes about the relationships between race, annual income, and drug use. What underlies common perceptions linking race, income, and drug use? With this study, we have explored those stereotypes and will tell you everything you need to know about how race and annual income actually influence drug use across the US. The results of our study are based on the National Survey on Drug Use and Health which was conducted in 2021. This survey asked people to report on their drug use, including information about the age when they first used a substance, how often they use it, and how likely they are to use it again in the future. The survey also collected information about the survey taker’s race, income, and location based on county size of where they are located.

The survey data is very comprehensive, but to focus on the results of our study, we have only looked at factors influencing the use of three substances: heroin, cocaine, and crack. Stereotypes often heard about these substances would be, for example: people with higher yearly incomes tend to use more cocaine, and people with lower yearly incomes would be more prone to using heroin or crack. We wanted to validate and potentially debunk these stereotypes via statistical models and tests that would test the data-based relationships between drug use, race, and income. For more details on those tests and models, please see the Analysis tab of our website. 

## Drug Exploration: Heroin, Cocaine, and Crack
After we had conducted our analysis, we found that there is a clear relationship between race and drug use. The bar chart indicates varying drug usage patterns among ethnic groups, with Native Americans/Alaska Natives having the highest percentage of people who have tried drugs, while Asians show the lowest. The boxplots examining the age of first drug use among different racial groups reveal variations. In terms of the age of first heroin use, Native Hawaiian/Other Pacific Islanders start early (around 10 years), whereas Asians have a significantly later initiation (around 29 years), the highest among all groups. Logistic regression analysis shows that Black/African Americans have a slightly higher likelihood of drug use, while Native American/Alaska Native populations exhibit the highest odds, emphasizing the need for targeted interventions to address these disparities.

## Income and Drug Use
We also found that there are relationships between income and drug use. Generally speaking, drugs, especially heroin or cocaine, are extremely expensive. So income is one of the important predictors that we need to consider. This perception may suggest that individuals with higher incomes could have more access to such substances due to their ability to afford them. Since the dependent variable that we apply (drug use), which outcome is binary, we utilized the logistic regression model for analyzing. By including and combining the ‘NEWRACE2’ and ‘income’, we were able to explore how these variables together can influence the drug use pattern. From the output table, the ‘Asian’ racial tends to have a lower odds of drug use while the native American is the highest. However, there are some interesting findings of the income levels. The data of the odds ratio indicates that with lower income levels showing a higher drug use. This is an unexpected result from the perceptions. In this case, the factors like socio-economic or psychological are what we need to consider. 

## Location and Drug Use
We were also interested in the relationship between location and drug use. We wanted to address the stereotypes that involve substance use and location. There are stereotypes such as “people in large cities/metropolitan areas tend to use more drugs like cocaine than people in rural counties”. We found that this is a claim that the NSDUH data supports. We found that more people use, on average, cocaine more days per week in large metro areas than those in small metro and non-metro areas. It was also found that more race categories use cocaine in a week in those large metro areas than those in non-large metro areas, with the Black/African American race category having the highest median number of days per week of use across all three metro classifications.

## Interpretations
We found some interesting trends between age and drug use as well. We have shown that on average, people try crack at a younger age then they try heroin. This could be due to a variety of factors, and interesting follow-up studies could involve access to those drugs and a survey of the average interest of people of a variety of ages in either drug. We would hypothesize that there is higher accessibility of crack to younger people, but that it is more difficult to acquire heroin. 

In conclusion, our comprehensive analysis of the 2021 National Survey on Drug Use and Health presents a nuanced understanding of the intricate web of factors influencing drug use in the United States. By debunking stereotypes and exploring the real data, we offer insights that can guide effective policy and intervention strategies. It's evident that drug use is not a monolithic issue but a complex interplay of racial, income, location, age, and societal factors. This understanding is crucial for developing targeted and effective approaches to address the challenges of drug abuse in various communities. Our study serves as a stepping stone for further research and discussion, aiming to contribute meaningfully to the ongoing efforts to combat substance abuse and its far-reaching impacts on society.

---

## Rubric: On this page

You will



* Title
  * Your big picture page should have a creative/click-bait-y title/headline that provides a hint about your thesis.
* Clarity of Explanation
  * You should have a clear thesis/goal for this page. What are you trying to show? Make sure that you explain your analysis in detail but don't go into top much mathematics or statistics. The audience for this page is the general public (to the extent possible). Your thesis should be a statement, not a question.
  * Each figure should be very polished and also not too complicated. There should be a clear interpretation of the figure so the figure has a clear purpose. Even something like a histogram can be difficult to interpret for non-experts.
* Creativity
  * Do your best to make things interesting. Think of a story. Think of how each part of your analysis supports the previous part or provides a different perspective.
* This page should be self-contained.
  
**Note**: This page should have no code visible, i.e. use `#| echo: FALSE`.  

