---
title: "Blog Post 6"
description:  |
  Wrapping the Project All Together (Part 1)
author: "Information Illumin8ors"
date: "2023-12-04"
categories: [Ending]
date-modified: "2023-12-04"
draft: FALSE
---
## EDA
We have uploaded excel files containing 2010 census information and 2009 CBSA codes, which the original survey makers/data collectors used to process location data information. We are working on merging the two right now to compare them to our existing data set. We have identified the counties/areas that appear both in the Census and CBSA data set. The next goal is to merge the census and CBSA data sets by lining up the information about each overlapping county so that we can get population totals for metro and non-metro areas since that is how location data is categorized in our data set. We know how many respondents come from metro versus non-metro areas, but now we will be able to guess at which counties those individuals come from. It will be interesting, once this is done, to use the geom_sf() function to visualize the spread and density of respondents by US geographical area and then to potentially use this to graph which areas have highest drug or alcohol use.

We have also explored multiple drugs and their relations to race and much can be seen about the relationships between the two. We are working on furthering this plot even further to depict the relationship between them better. Working on the Race vs Income predictor using linear regression model is also something we have explored because understanding a key relationship between these two variables help with the thesis and how we can support it and also explore the pitfalls of it. For instance, in the linear regression model, by encoding the race as a categorical variable and setting the income as the dependent variable, we would get the information given from this model. Then we could start model checking for further analysis like addressing Pitfalls. By finding the high correlation between these variables and addressing some issues, we would enhance the validity of our findings. One thing we have noticed about our dataset that limits us is how the survey was set up in that a respondent does not give a number for income but a range which hurts in creating unique values but we are able to make arrangements to go around this issue. We were really interested also in finding out more about how the data was being weighted based on how many people from each race responded to the survey. This is key in understanding more about the survey because it helps determine the representation of this dataset as well which can help with understanding our accuracy for the results given from plots and models.

We are looking forward to wrapping the EDA portion of the project but getting models and plots that really highlight what we are trying to tell to the public about the relationship between race and drug use. Hitting many dead ends as we were doing this project was something we had to overcome because sometimes the questions were skipped by respondents but we were able to find other questions that aligned with what we wanted to use. Being able to explain these plots and models is super important and we will use the plots to help showcase and break down the relationships found into elementary parts. 

## Tentative Thesis
Our tentative thesis is something along the lines of certain races tend to try or use drugs more than other races. Kinds of drugs favored are different per race. Certain cities/ rural areas have more or less drug use for certain races. A higher income could have more drug use or low income could have more drug use. We believe a strong and clear thesis from the data analysis we did because it explores important aspects in society that are not presented in the best manner to the public and understanding these differences can help with allocating resources towards those who need help and understanding where drug related problems can occur. Understanding the potential causes can help with addressing such causes as a public or through government. 

Some evidence that has already started to present itself is a logistic model created to show cigarette use and race and showing a simple difference between races in how many try cigarettes and use them. Simple models like this can help us go further in understanding whether location play a role in this difference or is it an income difference. Further exploration shows that both do in fact play a role. Whether a person is in a large metro or small metro or rural area is a big factor in what person does in terms of drug related options. Income is also a major factor in what is shown for drug use in that a person with higher income may tend to use more expensive drugs or certain types of drugs and this statement definitely has problems with it as well. Race can be associated with this and the location of whether it is a big city or not is seen to play a role in such a relationship. Being able to plot these relationships effectively is important in letting the general public and those interested in knowing more about this in effectively understanding the relationships. 

