---
title: "Blog Post 2"
description:  |
  Data for Equity Understanding for our Data Set
author: "Information Illumin8ors"
date: "2023-10-30"
categories: [Dataset Ethics and Equity]
date-modified: "2023-10-30"
draft: FALSE
---

  The principles emphasize the importance of considering the impact of data collection, analysis, and dissemination on the communities and individuals being studied. While our data analysis may not directly involve community interaction, we can apply these principles by ensuring that the data we use are collected and analyzed in a way that respects the principles of beneficence, respect for persons, and justice. This includes considering the potential benefits and harms of the data, being transparent about the data's limitations, and striving for a fair distribution of burdens and benefits.	

  Since we are not the ones actually collecting the data, we cannot really consider the principles in relation to that beyond choosing data sets from reputable and ethical sources, but we can think about the principles in their relation to data cleaning, visualization, and analysis. For example, we want to make sure we ask interesting but respectful/considerate questions for our analysis. We also want to make sure, while cleaning the data, that we do eliminate data that is relevant to the groups we are looking at, we do not want to be biased in cleaning our data because we want to keep our analysis representative of the survey participants. Adding on, being able to fairly assess and understand what the data is representing is key to not misinterpret and fall short in analysis. Transparency is key for the audience to understand how the data is being collected and shown so that misinterpretations can be minimized to the best possible degree.

  The principles of equitable data practice discussed in the article are: beneficence, justice, and respect for persons. When looking at our data set, we have to make sure that there is data available for a diverse range of different demographics. This idea ties into the justice principle because we want to make sure that our data represents multiple perspectives and communities. While our data includes data on income, age, health insurance, and race, it lacks detailed information on the location of the respondents. It would be good to supplement our data with another data set that gives us information about the general location demographics of the participants. Then, beneficence comes in because we want to be aware how sensitive topics can affect certain groups. Since our data concerns substance abuse and mental health disorders, we have to be sensitive when looking at the data and with the questions we decide to ask about it.

  Adhering to the practice of transparency would entail providing clear and comprehensive information about the data, including its limitations and potential sources of bias. It would involve documenting the data collection and analysis processes, making sure the data's context is well-understood, and acknowledging any potential misinterpretations or misuses of the data. Additionally, the principle of respect for persons would require obtaining informed consent when necessary and protecting the privacy of individuals whose data is used. This helps in maintaining respect amongst individuals for their data collected and also having privacy concerns lowered so that individuals do not fear their data is being used for the wrong purposes.
  
  In our analysis, it is possible that due to limited sample size, we were unable to collect a certain amount of data for each race. To address this, we could filter the data set to make sure we are analyzing a comparable amount of data for each race category to make sure we are not biasing the data or producing false data analysis. At the same time, the data itself may have limitations due to the fact that the respondents who can be contacted have similar identities to the investigators. In terms of potential abuse or misuse, if the data is not adequately protected, it could be accessed or used in ways that harm individuals or communities.

  There might be sampling bias. If the data is not representative of the entire population, conclusions drawn from it might not be generalizable. For instance, certain demographics might be underrepresented or over represented. Moreover, data related to substance use often relies on self-reporting, which can be subject to recall bias and social desirability bias. If not handled carefully, data on substance use can contribute to the stigmatization of individuals who use or have used substances, potentially leading to discrimination or other negative outcomes. Furthermore, Without proper context or understanding, the data can be misinterpreted. For example, high rates of substance use in a particular demographic might be wrongly attributed to cultural or inherent factors rather than socio-economic or environmental reasons. This can further cause divides and lead back to the topic of misinterpretation which hinder from the point that we as a group are trying to convey in our reports and plots.

	
